name: test

on:
    push:
    pull_request:

jobs:
    test:
        runs-on: windows-2022
        timeout-minutes: 20

        steps:
            - uses: actions/checkout@v2

            - name: Set up WSL
              uses: Vampire/setup-wsl@v1
              with:
                  distribution: Ubuntu-20.04
                  additional-packages: strace

            - name: Set up Rust
              shell: wsl-bash {0}
              run: curl https://sh.rustup.rs -sSf | sh -s -- -y

            - name: Check environment
              shell: wsl-bash {0}
              run: strace rustc --version

            - name: Build
              shell: wsl-bash {0}
              run: cargo build

            - name: Test
              shell: wsl-bash {0}
              run: cargo test

            - name: Run
              shell: wsl-bash {0}
              run: cargo run

            - name: Finish check
              run: echo "Check finished successfully!"
